routes/web.php
        Route::get('/receipt/{Document}', 'App\Http\Controllers\PrintController@getReceiptPdf')->name('pdf.receipt');
        Route::get('/nc/{Document}', 'App\Http\Controllers\PrintController@getNCPdf')->name('pdf.nc');
    });

    Route::group(['prefix' => 'accounting', 'middleware' => ['auth', 'check.factory']], function () {
        //index route
        Route::get('/', 'App\Http\Controllers\Accounting\AccountingController@index')->middleware(['auth'])->name('accounting');
        
        // Routes for Allocation
        Route::prefix('allocation')->group(function () {
            Route::post('/create', 'App\Http\Controllers\Accounting\AllocationController@store')->name('accounting.allocation.create');
            Route::post('/edit/{id}', 'App\Http\Controllers\Accounting\AllocationController@update')->name('accounting.allocation.update');
        });
    
        // Routes for Delivery
        Route::prefix('delivery')->group(function () {
            Route::post('/create', 'App\Http\Controllers\Accounting\DeliveryController@store')->name('accounting.delivery.create');
            Route::post('/edit/{id}', 'App\Http\Controllers\Accounting\DeliveryController@update')->name('accounting.delivery.update');
        });
    
        // Routes for Payment Conditions
        Route::prefix('paymentCondition')->group(function () {
            Route::post('/create', 'App\Http\Controllers\Accounting\PaymentConditionsController@store')->name('accounting.paymentCondition.create');
            Route::post('/edit/{id}', 'App\Http\Controllers\Accounting\PaymentConditionsController@update')->name('accounting.paymentCondition.update');
        });
    
        // Routes for Payment Methods
        Route::prefix('paymentMethod')->group(function () {
            Route::post('/create', 'App\Http\Controllers\Accounting\PaymentMethodController@store')->name('accounting.paymentMethod.create');
            Route::post('/edit/{id}', 'App\Http\Controllers\Accounting\PaymentMethodController@update')->name('accounting.paymentMethod.update');
        });
    
        // Routes for VAT
        Route::prefix('vat')->group(function () {
            Route::post('/create', 'App\Http\Controllers\Accounting\VatController@store')->name('accounting.vat.create');
            Route::post('/edit/{id}', 'App\Http\Controllers\Accounting\VatController@update')->name('accounting.vat.update');
        }); });

        Route::group(['prefix' => 'times', 'middleware' => ['auth', 'check.factory']], function () {
            // Index route
            Route::get('/', 'App\Http\Controllers\Times\TimesController@index')->name('times');
        
            // Absence routes
            Route::group(['prefix' => 'absence'], function () {
                Route::post('/create', 'App\Http\Controllers\Times\AbsenceController@store')->name('times.absence.create');
                Route::post('/edit/{id}', 'App\Http\Controllers\Times\AbsenceController@update')->name('times.absence.update');
            });
        
            // Bank Holiday routes
            Route::group(['prefix' => 'banckholiday'], function () {
                Route::post('/create', 'App\Http\Controllers\Times\BanckHolidayController@store')->name('times.banckholiday.create');
                Route::post('/edit/{id}', 'App\Http\Controllers\Times\BanckHolidayController@update')->name('times.banckholiday.update');
            });
        
            // ImproductTime routes
            Route::group(['prefix' => 'improducttime'], function () {
                Route::post('/create', 'App\Http\Controllers\Times\ImproductTimeController@store')->name('times.improducttime.create');
                Route::post('/edit/{id}', 'App\Http\Controllers\Times\ImproductTimeController@update')->name('times.improducttime.update');
            });
        
            // MachineEvent routes
            Route::group(['prefix' => 'machineevent'], function () {
                Route::post('/create', 'App\Http\Controllers\Times\MachineEventController@store')->name('times.machineevent.create');
                Route::post('/edit/{id}', 'App\Http\Controllers\Times\MachineEventController@update')->name('times.machineevent.update');
            });
        });

    Route::group(['prefix' => 'products', 'middleware' => ['auth', 'check.factory']], function () {
        //index product route
        Route::get('/', 'App\Http\Controllers\Products\ProductsController@index')->name('products');

        //product route 
        Route::post('/create', 'App\Http\Controllers\Products\ProductsController@store')->name('products.store');
        Route::post('/supplier', 'App\Http\Controllers\Products\ProductsController@StoreSupplier')->name('products.supplier.create');
        Route::post('/edit/{id}', 'App\Http\Controllers\Products\ProductsController@update')->name('products.update');
        Route::get('/duplicate/{id}', 'App\Http\Controllers\Products\ProductsController@duplicate')->name('products.duplicate');
        Route::post('/image', 'App\Http\Controllers\Products\ProductsController@StoreImage')->name('products.update.image');
        Route::post('/drawing', 'App\Http\Controllers\Products\ProductsController@StoreDrawing')->name('products.update.drawing');
        Route::post('/stl', 'App\Http\Controllers\Products\ProductsController@StoreStl')->name('products.update.stl');
        Route::post('/svg', 'App\Http\Controllers\Products\ProductsController@StoreSVG')->name('products.update.svg');

        // Stock routes
        Route::group(['prefix' => 'Stock'], function () {
            Route::get('/', 'App\Http\Controllers\Products\StockController@index')->name('products.stock');
            Route::post('/create', 'App\Http\Controllers\Products\StockController@store')->name('products.stock.store');
            Route::post('/edit/{id}', 'App\Http\Controllers\Products\StockController@update')->name('products.stock.update');
            Route::get('/{id}', 'App\Http\Controllers\Products\StockController@show')->name('products.stock.show');
        });

        // Stock Location routes
        Route::group(['prefix' => 'stock/location'], function () {
            Route::post('/create', 'App\Http\Controllers\Products\StockLocationController@store')->name('products.stocklocation.store');
            Route::post('/edit/{id}', 'App\Http\Controllers\Products\StockLocationController@update')->name('products.stocklocation.update');
            Route::get('/{id}', 'App\Http\Controllers\Products\StockLocationController@show')->name('products.stocklocation.show');
        });

        // Stock Location Products routes
        Route::group(['prefix' => 'stock/location/product'], function () {
            Route::post('/create', 'App\Http\Controllers\Products\StockLocationProductsController@store')->name('products.stockline.store');
            Route::post('/create/internal-order', 'App\Http\Controllers\Products\StockLocationProductsController@storeFromInternalOrder')->name('products.stockline.store.from.internal.order');
            Route::post('/create/purchase-order', 'App\Http\Controllers\Products\StockLocationProductsController@storeFromPurchaseOrder')->name('products.stockline.store.from.purchase.order');
            Route::post('/edit/{id}', 'App\Http\Controllers\Products\StockLocationProductsController@update')->name('products.stockline.update');
            Route::get('/{id}', 'App\Http\Controllers\Products\StockLocationProductsController@show')->name('products.stockline.show');
            Route::post('/entry', 'App\Http\Controllers\Products\StockLocationProductsController@entry')->name('products.stockline.manual.entry');
            Route::post('/entry/internal-order', 'App\Http\Controllers\Products\StockLocationProductsController@entryFromInternalOrder')->name('products.stockline.entry.from.internal.order');
            Route::post('/entry/purchase-order', 'App\Http\Controllers\Products\StockLocationProductsController@entryFromPurchaseOrder')->name('products.stockline.entry.from.purchase.order');
            Route::post('/sorting', 'App\Http\Controllers\Products\StockLocationProductsController@sorting')->name('products.stockline.sorting');
        });
        
        Route::get('/{id}', 'App\Http\Controllers\Products\ProductsController@show')->name('products.show');
    });

    Route::group(['prefix' => 'task', 'middleware' => ['auth', 'check.factory']], function () {
        Route::put('/sync', 'App\Http\Controllers\Planning\TaskController@sync')->name('task.sync');
        Route::get('/{id_type}/{id_page}/show/{id_line}', 'App\Http\Controllers\Planning\TaskController@manage')->name('task.manage');
        Route::get('/{id_type}/{id_page}/delete/{id_task}', 'App\Http\Controllers\Planning\TaskController@delete')->name('task.delete');
        Route::post('/create/{id}', 'App\Http\Controllers\Planning\TaskController@store')->name('task.store');
        Route::post('/update/{id}', 'App\Http\Controllers\Planning\TaskController@update')->name('task.update');
    });


    Route::group(['prefix' => 'production', 'middleware' => ['auth', 'check.factory', 'check.task.status']], function () {
        Route::get('/Task/Statu/Id/{id}', 'App\Http\Controllers\Planning\TaskController@statu')->name('production.task.statu.id');
        Route::get('/Task/Statu', 'App\Http\Controllers\Planning\TaskController@statu')->name('production.task.statu');
        Route::get('/Task', 'App\Http\Controllers\Planning\TaskController@index')->name('production.task');
        Route::get('/kanban', 'App\Http\Controllers\Planning\TaskController@kanban')->name('production.kanban');
        Route::get('/calendar', 'App\Http\Controllers\Planning\CalendarController@index')->name('production.calendar');
        Route::get('/gantt', 'App\Http\Controllers\Planning\GanttController@index')->name('production.gantt');
        
        Route::get('/load-planning', 'App\Http\Controllers\Planning\PlanningController@index')->name('production.load.planning');
    });

app/Models/Products/Inventory.php
<?php

namespace App\Models\Products;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;

    protected $fillable = ['code',
                          'label', 
                          'start_date',
                          'end_date',
                          'label'];
  
    public function GetPrettyCreatedAttribute()
    {
        return date('d F Y', strtotime($this->created_at));
    }
                          
}

app/Http/Controllers/Products/Controller.php
<?php

namespace App\Http\Controllers\Products;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Products/InventoryController.php
<?php

namespace App\Http\Controllers\Products;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class InventoryController extends Controller
{
    //
}

app/Http/Controllers/Products/InventoryDetailController.php
<?php

namespace App\Http\Controllers\Products;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class InventoryDetailController extends Controller
{
    //
}

app/Http/Controllers/Products/StockController.php
<?php

namespace App\Http\Controllers\Products;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Products\Stocks;
use App\Models\Products\Products;
use Illuminate\Support\Facades\DB;
use App\Models\Workflow\OrderLines;
use App\Services\SelectDataService;
use App\Http\Controllers\Controller;
use App\Models\Products\StockLocation;
use App\Models\Products\StockLocationProducts;
use App\Http\Requests\Products\StoreStockRequest;
use App\Http\Requests\Products\UpdateStockRequest;

class StockController extends Controller
{
    
    protected $SelectDataService;
    public function __construct(SelectDataService $SelectDataService)
    {
        $this->SelectDataService = $SelectDataService;
    }

    //
    public function index()
    {
        $stocks = Stocks::withCount('StockLocation')->get();
        $userSelect = $this->SelectDataService->getUsers();
        $LastStock =  DB::table('stocks')->orderBy('id', 'desc')->first();
        $StockLocationList = StockLocation::all();
        $StockLocationProductList = StockLocationProducts::all();

        //Select order line where not delivered or partialy delivered
        $InternalOrderRequestsLineslist = OrderLines::where(
                                                        function($query) {
                                                            return $query
                                                                ->where('delivery_status', '=', '1')
                                                                ->orWhere('delivery_status', '=', '2');
                                                        })
                                                    ->whereHas('order', function($q){
                                                        $q->where('type', '=', '2');
                                                    })->get();

        return view('products/stocks-index', [
            'stocks' => $stocks,
            'userSelect' => $userSelect,
            'LastStock' => $LastStock,
            'StockLocationList' => $StockLocationList,
            'StockLocationProductList' => $StockLocationProductList,
            'InternalOrderRequestsLineslist' => $InternalOrderRequestsLineslist
        ]);
    }

    public function store(StoreStockRequest $request)
    {
        $Stock = Stocks::create($request->only('code','label', 'user_id'));
        return redirect()->route('products.stock.show', ['id' => $Stock->id])->with('success', 'Successfully created new stock');
    }

    public function show($id)
    {
        $Stock = Stocks::findOrFail($id);
        $StockLocations = StockLocation::withCount('StockLocationProducts')->where('stocks_id', '=', $id)->get();
        $userSelect = $this->SelectDataService->getUsers();
        $LastStockLocation =  DB::table('stock_locations')->orderBy('id', 'desc')->first();
        
        return view('products/stock-show', [
            'Stock' => $Stock,
            'StockLocations' => $StockLocations,
            'userSelect' => $userSelect,
            'LastStockLocation' => $LastStockLocation
        ]);
    }

    /**
     * @param $request
     * @return View
     */
    public function update(UpdateStockRequest $request)
    {
        $Stock = Stocks::find($request->id);
        $Stock->label=$request->label;
        $Stock->user_id=$request->user_id;
        $Stock->save();
        return redirect()->route('products.stock')->with('success', 'Successfully updated stock '.  $Stock->label);
    }
}

app/Http/Controllers/Products/StockLocationController.php
<?php

namespace App\Http\Controllers\Products;

use App\Models\User;
use Illuminate\Http\Request;
use App\Models\Products\Stocks;
use App\Models\Products\Products;
use Illuminate\Support\Facades\DB;
use App\Services\SelectDataService;
use App\Http\Controllers\Controller;
use App\Models\Products\StockLocation;
use App\Models\Products\StockLocationProducts;
use App\Http\Requests\Products\StoreStockLocationRequest;
use App\Http\Requests\Products\UpdateStockLocationRequest;

class StockLocationController extends Controller
{
    protected $SelectDataService;
    public function __construct(SelectDataService $SelectDataService)
    {
        $this->SelectDataService = $SelectDataService;
    }
    //
    public function show($id)
    {
        $StockLocation = StockLocation::findOrFail($id);
        $Stock = Stocks::findOrFail($StockLocation->stocks_id);
        $StockLocationsProducts = StockLocationProducts::where('stock_locations_id', '=', $id)->get();
        $userSelect = $this->SelectDataService->getUsers();
        $ProductSelect = Products::select('id', 'code')->get();
        $LastStockLocationProduct =  DB::table('stock_location_products')->orderBy('id', 'desc')->first();
        
        return view('products/stockLocation-show', [
            'Stock' => $Stock,
            'StockLocation' => $StockLocation,
            'StockLocationsProducts' => $StockLocationsProducts,
            'userSelect' => $userSelect,
            'ProductSelect' => $ProductSelect,
            'LastStockLocationProduct' => $LastStockLocationProduct
        ]);
    }

    public function store(StoreStockLocationRequest $request)
    {
        $StockLocation = StockLocation::create($request->only('code',
                                                'label', 
                                                'stocks_id',
                                                'user_id',
                                                'end_date',
                                                'comment',
                                            ));

        return redirect()->route('products.stocklocation.show', ['id' => $StockLocation->id])->with('success', 'Successfully created new location stock');
    }

    /**
     * @param $request
     * @return View
     */
    public function update(UpdateStockLocationRequest $request)
    {
        $StockLocation = StockLocation::find($request->id);
        $StockLocation->label=$request->label;
        $StockLocation->user_id=$request->user_id;
        $StockLocation->comment=$request->comment;
        $StockLocation->save();
        return redirect()->route('products.stock.show', ['id' => $request->stocks_id])->with('success', 'Successfully updated stock location'.  $StockLocation->label);
    }
}

resources/views/products/products-index.blade.php
@extends('adminlte::page')

@section('title', __('general_content.products_trans_key'))

@section('content_header')
<div class="row mb-2">
  <h1>{{__('general_content.product_list_trans_key')}}</h1>
</div>
@stop

@section('right-sidebar')

@section('content')
  @livewire('products-index')
@stop

@section('css')
@stop

@section('js')
@stop

resources/views/products/stock-show.blade.php
@extends('adminlte::page')

@section('title', __('general_content.stock_trans_key')) 

@section('content_header')
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>{{ $Stock->label }} {{ __('general_content.stock_trans_key') }}</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('products.stock') }}">{{ __('general_content.stock_list_trans_key') }}</a></li>
        </ol>
    </div>
  </div>
@stop

@section('content')
  @include('include.alert-result')
    <div class="card card-primary">
      <div class="card-body">
        <div class="row">
          <div class="col-md-6 card-primary">
            <div class="card-header">
                <h3 class="card-title">{{ __('general_content.stock_location_list_trans_key') }}</h3>
            </div>
            <div class="card-body table-responsive p-0">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>{{__('general_content.id_trans_key') }}</th>
                    <th>{{__('general_content.label_trans_key') }}</th>
                    <th>{{__('general_content.lines_count_trans_key') }}</th>
                    <th>{{ __('general_content.end_date_trans_key') }}</th>
                    <th>{{ __('general_content.user_management_trans_key') }}</th>
                    <th>{{__('general_content.action_trans_key') }}</th>
                  </tr>
                </thead>
                <tbody>
                  @forelse ($StockLocations as $StockLocation)
                  <tr>
                    <td>{{ $StockLocation->code }}</td>
                    <td>{{ $StockLocation->label }}</td>
                    <td>{{ $StockLocation->stock_location_products_count }}</td>
                    <td>{{ $StockLocation->end_date }}</td>
                    <td>{{ $StockLocation->UserManagement['name'] }}</td>
                    <td class=" py-0 align-middle">
                      <div class="btn-group btn-group-sm">
                        <a href="{{ route('products.stocklocation.show', ['id' => $StockLocation->id])}}" class="btn btn-info"><i class="fa fa-lg fa-fw fa-eye"></i></a>
                      </div>
                      <!-- Button Modal -->
                      <button type="button" class="btn bg-teal" data-toggle="modal" data-target="#StockLocation{{ $StockLocation->id }}">
                        <i class="fa fa-lg fa-fw  fa-edit"></i>
                      </button>
                      <!-- Modal {{ $StockLocation->id }} -->
                      <x-adminlte-modal id="StockLocation{{ $StockLocation->id }}" title="Update {{ $StockLocation->label }}" theme="teal" icon="fa fa-pen" size='lg' disable-animations>
                        <form method="POST" action="{{ route('products.stocklocation.update', ['id' => $StockLocation->id]) }}" >
                          @csrf
                          <div class="card-body">
                            <div class="form-group">
                              <label for="label">{{__('general_content.label_trans_key') }}</label>
                              <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-tags"></i></span>
                                </div>
                                <input type="text" class="form-control" name="label"  id="label" placeholder="{{__('general_content.label_trans_key') }}" value="{{ $StockLocation->label }}">
                                <input type="hidden" name="stocks_id"  id="stocks_id"  value="{{ $StockLocation->stocks_id }}">
                              </div>
                            </div>
                            <div class="form-group">
                              <label for="service_id">{{ __('general_content.user_management_trans_key') }}</label>
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text"><i class="fas fa-list"></i></span>
                                </div>
                                  <select class="form-control" name="user_id" id="user_id">
                                    @foreach ($userSelect as $item)
                                    <option value="{{ $item->id }}" @if($StockLocation->user_id == $item->id  ) Selected @endif>{{ $item->name }}</option>
                                    @endforeach
                                  </select>
                              </div>
                            </div>
                            <div class="form-group">
                              <label>{{ __('general_content.comment_trans_key') }}</label>
                              <textarea class="form-control" rows="3" name="comment"  placeholder="...">{{ $StockLocation->comment }}</textarea>
                            </div>
                          </div>
                          <div class="card-footer">
                            <x-adminlte-button class="btn-flat" type="submit" label="{{ __('general_content.update_trans_key') }}" theme="info" icon="fas fa-lg fa-save"/>
                          </div>
                        </form>
                      </x-adminlte-modal>
                    </td>
                  </tr>
                  @empty
                    <x-EmptyDataLine col="5" text="{{ __('general_content.no_data_trans_key') }}"  />
                  @endforelse
                </tbody>
                <tfoot>
                  <tr>
                    <th>{{__('general_content.id_trans_key') }}</th>
                    <th>{{__('general_content.label_trans_key') }}</th>
                    <th>{{__('general_content.lines_count_trans_key') }}</th>
                    <th>{{ __('general_content.end_date_trans_key') }}</th>
                    <th>{{ __('general_content.user_management_trans_key') }}</th>
                    <th>{{__('general_content.action_trans_key') }}</th>
                  </tr>
                </tfoot>
              </table>
            </div>
          <!-- /.card secondary -->
          </div>
          <div class="col-md-6 card-secondary">
              <div class="card-header">
                <h3 class="card-title">{{ __('general_content.new_stock_location_trans_key') }}</h3>
              </div>
              <div class="card-body">
                <form  method="POST" action="{{ route('products.stocklocation.store') }}" class="form-horizontal">
                  @csrf
                  <div class="form-group">
                    <label for="code">{{ __('general_content.external_id_trans_key') }}</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                          <span class="input-group-text"><i class="fas fa-external-link-square-alt"></i></span>
                      </div>
                      <input type="text" class="form-control" name="code" id="code" placeholder="{{ __('general_content.external_id_trans_key') }}" value="STOCK-LOCATION-{{ $LastStockLocation->id ?? '0' }}">
                      <input type="hidden" name="stocks_id" id="stocks_id" value="{{ $Stock->id }}">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="label">{{ __('general_content.description_trans_key') }}</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                          <span class="input-group-text"><i class="fas fa-tags"></i></span>
                      </div>
                      <input type="text" class="form-control" name="label" id="label" placeholder="Description">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="user_id">{{ __('general_content.user_management_trans_key') }}</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                      </div>
                      <select class="form-control" name="user_id" id="user_id">
                        @foreach ($userSelect as $item)
                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="end_date">{{ __('general_content.end_date_trans_key') }}</label>
                    <input type="date" class="form-control" name="end_date"  id="end_date" >
                  </div>
                  <div class="form-group">
                    <label>{{ __('general_content.comment_trans_key') }}</label>
                    <textarea class="form-control" rows="3" name="comment"  placeholder="..."></textarea>
                  </div>
                  <div class="card-footer">
                    <x-adminlte-button class="btn-flat" type="submit" label="{{ __('general_content.submit_trans_key') }}" theme="danger" icon="fas fa-lg fa-save"/>
                  </div>
                </form>
              <!-- /.card body -->
              </div>
            <!-- /.card secondary -->
            </div>
          <!-- /.row -->
          </div>
        <!-- /.card body -->
        </div>
      <!-- /.card primary -->
      </div>

@stop

@section('css')
@stop

@section('js')
@stop